// This file is generated by Slice Machine. Update with care!

import MyFirstSlic from './MyFirstSlic';
import MyFourthSlice from './MyFourthSlice';
import MyThirdSliceForRepeat from './MyThirdSliceForRepeat';
import RighTextSlide from './RighTextSlide';
import SecondSliceDemo from './SecondSliceDemo';

export {
	MyFirstSlic,
	MyFourthSlice,
	MyThirdSliceForRepeat,
	RighTextSlide,
	SecondSliceDemo,
};

export const components = {
	my_first_slic: MyFirstSlic,
	my_fourth_slice: MyFourthSlice,
	my_third_slice_for_repeat: MyThirdSliceForRepeat,
	righ_text_slide: RighTextSlide,
	second_slice_demo: SecondSliceDemo,
};
